// <auto-generated />
namespace Humberto.Musicas.AcessoDados.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InicioDeTudo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InicioDeTudo));
        
        string IMigrationMetadata.Id
        {
            get { return "201804021306011_InicioDeTudo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
